name: Pipeline Desafio 2026

on:
  push:
    branches:
      - prod
      - dev
      - hml
    tags:
      - 'v*'      

env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
  DOCKERHUB_USERNAME_V2: rodrigorootrjportifolio

jobs:

  check-env:
    name: Check Environment
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name == 'dev' && 'dev'|| github.ref_name == 'hml' && 'hml' || github.ref_name == 'prod' && 'prod' }}

    steps:
      - name: Check DockerHub Username
        if: ${{ env.DOCKERHUB_USERNAME != '' }}
        run: |
          echo "DOCKERHUB_USERNAME possui conteúdo"

      - name: Check Flask Cache Timeout
        if: ${{ env.FLASK_LOCAL_CACHE_DEFAULT_TIMEOUT != '' }}
        run: |
          echo "FLASK_LOCAL_CACHE_DEFAULT_TIMEOUT possui conteúdo"


  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name == 'dev' && 'dev'|| github.ref_name == 'hml' && 'hml' || github.ref_name == 'prod' && 'prod' }}

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4


  deploy:  
    uses: rodrigorootrjportfolio/pipelines/.github/workflows/docker-hub-registry.yaml@main
    with:
      ENVIRONMENT: 'prod'
      REGISTRY: ${{ vars.registry }}
      DOCKERHUB_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ vars.DOCKERHUB_TOKEN }}
      DOCKER_PROJETO: ${{ vars.DOCKER_PROJETO }}
      RELEASE: ${{ vars.RELEASE }}
      CODE_ENV: ${{ vars.CODE_ENV }}
      FLASK_LOCAL_CACHE_DEFAULT_TIMEOUT: ${{ vars.FLASK_LOCAL_CACHE_DEFAULT_TIMEOUT }}
    secrets:
      REGISTRY_USERNAME: ${{ secrets.GITHUB_TOKEN }}
      